# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_prac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='degree',
            field=models.IntegerField(default=0),
        ),
    ]
