# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_prac', '0004_auto_20170507_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to='%Y/%m/%d/orig'),
        ),
    ]
