# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_prac', '0006_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume_prac.Person'),
        ),
    ]
