# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_prac', '0008_auto_20170520_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_oneline',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
