# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_prac', '0009_person_person_oneline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='endDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='startDate',
            field=models.DateField(blank=True),
        ),
    ]
