# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_prac', '0010_auto_20170521_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='resume_prac.Tag'),
        ),
    ]
