# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_prac', '0011_auto_20170521_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='publishDate',
            field=models.DateField(auto_now=True),
        ),
    ]
