# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_prac', '0012_experience_publishdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fb_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gb_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
