# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_prac', '0013_auto_20170528_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fb_url',
            field=models.TextField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gb_url',
            field=models.TextField(blank=True, default='#', null=True),
        ),
    ]
