# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_prac', '0014_auto_20170528_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='ex_sub',
            field=models.TextField(blank=True, null=True),
        ),
    ]
